//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace Sconit_SMARTDEVICE.SconitWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmartDeviceMgrWSSoap", Namespace="http://com.Sconit.Webservice")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    public partial class SmartDeviceMgrWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ScanBarcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadUserPerferenceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SmartDeviceMgrWS() {
            this.Url = global::Sconit_SMARTDEVICE.Properties.Settings.Default.Sconit_SMARTDEVICE_SconitWS_SmartDeviceMgrWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ScanBarcodeCompletedEventHandler ScanBarcodeCompleted;
        
        /// <remarks/>
        public event LoadUserCompletedEventHandler LoadUserCompleted;
        
        /// <remarks/>
        public event GetUserPermissionsCompletedEventHandler GetUserPermissionsCompleted;
        
        /// <remarks/>
        public event LoadUserPerferenceCompletedEventHandler LoadUserPerferenceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://com.Sconit.Webservice/ScanBarcode", RequestNamespace="http://com.Sconit.Webservice", ResponseNamespace="http://com.Sconit.Webservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resolver ScanBarcode(Resolver resolver) {
            object[] results = this.Invoke("ScanBarcode", new object[] {
                        resolver});
            return ((Resolver)(results[0]));
        }
        
        /// <remarks/>
        public void ScanBarcodeAsync(Resolver resolver) {
            this.ScanBarcodeAsync(resolver, null);
        }
        
        /// <remarks/>
        public void ScanBarcodeAsync(Resolver resolver, object userState) {
            if ((this.ScanBarcodeOperationCompleted == null)) {
                this.ScanBarcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScanBarcodeOperationCompleted);
            }
            this.InvokeAsync("ScanBarcode", new object[] {
                        resolver}, this.ScanBarcodeOperationCompleted, userState);
        }
        
        private void OnScanBarcodeOperationCompleted(object arg) {
            if ((this.ScanBarcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ScanBarcodeCompleted(this, new ScanBarcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://com.Sconit.Webservice/LoadUser", RequestNamespace="http://com.Sconit.Webservice", ResponseNamespace="http://com.Sconit.Webservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User LoadUser(string userCode) {
            object[] results = this.Invoke("LoadUser", new object[] {
                        userCode});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void LoadUserAsync(string userCode) {
            this.LoadUserAsync(userCode, null);
        }
        
        /// <remarks/>
        public void LoadUserAsync(string userCode, object userState) {
            if ((this.LoadUserOperationCompleted == null)) {
                this.LoadUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadUserOperationCompleted);
            }
            this.InvokeAsync("LoadUser", new object[] {
                        userCode}, this.LoadUserOperationCompleted, userState);
        }
        
        private void OnLoadUserOperationCompleted(object arg) {
            if ((this.LoadUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadUserCompleted(this, new LoadUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://com.Sconit.Webservice/GetUserPermissions", RequestNamespace="http://com.Sconit.Webservice", ResponseNamespace="http://com.Sconit.Webservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permission[] GetUserPermissions(string categoryCode, string userCode) {
            object[] results = this.Invoke("GetUserPermissions", new object[] {
                        categoryCode,
                        userCode});
            return ((Permission[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPermissionsAsync(string categoryCode, string userCode) {
            this.GetUserPermissionsAsync(categoryCode, userCode, null);
        }
        
        /// <remarks/>
        public void GetUserPermissionsAsync(string categoryCode, string userCode, object userState) {
            if ((this.GetUserPermissionsOperationCompleted == null)) {
                this.GetUserPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPermissionsOperationCompleted);
            }
            this.InvokeAsync("GetUserPermissions", new object[] {
                        categoryCode,
                        userCode}, this.GetUserPermissionsOperationCompleted, userState);
        }
        
        private void OnGetUserPermissionsOperationCompleted(object arg) {
            if ((this.GetUserPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPermissionsCompleted(this, new GetUserPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://com.Sconit.Webservice/LoadUserPerference", RequestNamespace="http://com.Sconit.Webservice", ResponseNamespace="http://com.Sconit.Webservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserPreference LoadUserPerference(string userCode, string preCode) {
            object[] results = this.Invoke("LoadUserPerference", new object[] {
                        userCode,
                        preCode});
            return ((UserPreference)(results[0]));
        }
        
        /// <remarks/>
        public void LoadUserPerferenceAsync(string userCode, string preCode) {
            this.LoadUserPerferenceAsync(userCode, preCode, null);
        }
        
        /// <remarks/>
        public void LoadUserPerferenceAsync(string userCode, string preCode, object userState) {
            if ((this.LoadUserPerferenceOperationCompleted == null)) {
                this.LoadUserPerferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadUserPerferenceOperationCompleted);
            }
            this.InvokeAsync("LoadUserPerference", new object[] {
                        userCode,
                        preCode}, this.LoadUserPerferenceOperationCompleted, userState);
        }
        
        private void OnLoadUserPerferenceOperationCompleted(object arg) {
            if ((this.LoadUserPerferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadUserPerferenceCompleted(this, new LoadUserPerferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class Resolver : EntityBase {
        
        private string moduleTypeField;
        
        private string userCodeField;
        
        private string codePrefixField;
        
        private string barcodeHeadField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string statusField;
        
        private string pickByField;
        
        private string inputField;
        
        private string binCodeField;
        
        private bool isOddCreateHuField;
        
        private bool isScanHuField;
        
        private bool needPrintAsnField;
        
        private bool needPrintReceiptField;
        
        private bool autoPrintHuField;
        
        private bool allowExceedField;
        
        private bool allowCreateDetailField;
        
        private bool isPickFromBinField;
        
        private string iOTypeField;
        
        private string commandField;
        
        private string resultField;
        
        private string orderTypeField;
        
        private string antiResolveHuField;
        
        private string printUrlField;
        
        private string externalOrderNoField;
        
        private string locationCodeField;
        
        private string locationFormCodeField;
        
        private string locationToCodeField;
        
        private Transformer[] transformersField;
        
        private ReceiptNote[] receiptNotesField;
        
        private string[][] workingHoursField;
        
        /// <remarks/>
        public string ModuleType {
            get {
                return this.moduleTypeField;
            }
            set {
                this.moduleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CodePrefix {
            get {
                return this.codePrefixField;
            }
            set {
                this.codePrefixField = value;
            }
        }
        
        /// <remarks/>
        public string BarcodeHead {
            get {
                return this.barcodeHeadField;
            }
            set {
                this.barcodeHeadField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string PickBy {
            get {
                return this.pickByField;
            }
            set {
                this.pickByField = value;
            }
        }
        
        /// <remarks/>
        public string Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
        
        /// <remarks/>
        public string BinCode {
            get {
                return this.binCodeField;
            }
            set {
                this.binCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOddCreateHu {
            get {
                return this.isOddCreateHuField;
            }
            set {
                this.isOddCreateHuField = value;
            }
        }
        
        /// <remarks/>
        public bool IsScanHu {
            get {
                return this.isScanHuField;
            }
            set {
                this.isScanHuField = value;
            }
        }
        
        /// <remarks/>
        public bool NeedPrintAsn {
            get {
                return this.needPrintAsnField;
            }
            set {
                this.needPrintAsnField = value;
            }
        }
        
        /// <remarks/>
        public bool NeedPrintReceipt {
            get {
                return this.needPrintReceiptField;
            }
            set {
                this.needPrintReceiptField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoPrintHu {
            get {
                return this.autoPrintHuField;
            }
            set {
                this.autoPrintHuField = value;
            }
        }
        
        /// <remarks/>
        public bool AllowExceed {
            get {
                return this.allowExceedField;
            }
            set {
                this.allowExceedField = value;
            }
        }
        
        /// <remarks/>
        public bool AllowCreateDetail {
            get {
                return this.allowCreateDetailField;
            }
            set {
                this.allowCreateDetailField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPickFromBin {
            get {
                return this.isPickFromBinField;
            }
            set {
                this.isPickFromBinField = value;
            }
        }
        
        /// <remarks/>
        public string IOType {
            get {
                return this.iOTypeField;
            }
            set {
                this.iOTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AntiResolveHu {
            get {
                return this.antiResolveHuField;
            }
            set {
                this.antiResolveHuField = value;
            }
        }
        
        /// <remarks/>
        public string PrintUrl {
            get {
                return this.printUrlField;
            }
            set {
                this.printUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalOrderNo {
            get {
                return this.externalOrderNoField;
            }
            set {
                this.externalOrderNoField = value;
            }
        }
        
        /// <remarks/>
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocationFormCode {
            get {
                return this.locationFormCodeField;
            }
            set {
                this.locationFormCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocationToCode {
            get {
                return this.locationToCodeField;
            }
            set {
                this.locationToCodeField = value;
            }
        }
        
        /// <remarks/>
        public Transformer[] Transformers {
            get {
                return this.transformersField;
            }
            set {
                this.transformersField = value;
            }
        }
        
        /// <remarks/>
        public ReceiptNote[] ReceiptNotes {
            get {
                return this.receiptNotesField;
            }
            set {
                this.receiptNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] WorkingHours {
            get {
                return this.workingHoursField;
            }
            set {
                this.workingHoursField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class Transformer : EntityBase {
        
        private int idField;
        
        private int orderLocTransIdField;
        
        private string orderNoField;
        
        private int sequenceField;
        
        private string itemCodeField;
        
        private string itemDescriptionField;
        
        private string referenceItemCodeField;
        
        private string uomCodeField;
        
        private decimal unitCountField;
        
        private string locationFromCodeField;
        
        private string locationToCodeField;
        
        private string storageBinCodeField;
        
        private string lotNoField;
        
        private decimal orderedQtyField;
        
        private decimal shippedQtyField;
        
        private decimal receivedQtyField;
        
        private int locationLotDetIdField;
        
        private string oddShipOptionField;
        
        private string locationCodeField;
        
        private decimal qtyField;
        
        private decimal currentQtyField;
        
        private decimal currentRejectQtyField;
        
        private decimal scrapQtyField;
        
        private decimal rejectedQtyField;
        
        private int cartonsField;
        
        private int operationField;
        
        private decimal adjustQtyField;
        
        private TransformerDetail[] transformerDetailsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int OrderLocTransId {
            get {
                return this.orderLocTransIdField;
            }
            set {
                this.orderLocTransIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceItemCode {
            get {
                return this.referenceItemCodeField;
            }
            set {
                this.referenceItemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UomCode {
            get {
                return this.uomCodeField;
            }
            set {
                this.uomCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitCount {
            get {
                return this.unitCountField;
            }
            set {
                this.unitCountField = value;
            }
        }
        
        /// <remarks/>
        public string LocationFromCode {
            get {
                return this.locationFromCodeField;
            }
            set {
                this.locationFromCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocationToCode {
            get {
                return this.locationToCodeField;
            }
            set {
                this.locationToCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StorageBinCode {
            get {
                return this.storageBinCodeField;
            }
            set {
                this.storageBinCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LotNo {
            get {
                return this.lotNoField;
            }
            set {
                this.lotNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrderedQty {
            get {
                return this.orderedQtyField;
            }
            set {
                this.orderedQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ShippedQty {
            get {
                return this.shippedQtyField;
            }
            set {
                this.shippedQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ReceivedQty {
            get {
                return this.receivedQtyField;
            }
            set {
                this.receivedQtyField = value;
            }
        }
        
        /// <remarks/>
        public int LocationLotDetId {
            get {
                return this.locationLotDetIdField;
            }
            set {
                this.locationLotDetIdField = value;
            }
        }
        
        /// <remarks/>
        public string OddShipOption {
            get {
                return this.oddShipOptionField;
            }
            set {
                this.oddShipOptionField = value;
            }
        }
        
        /// <remarks/>
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrentQty {
            get {
                return this.currentQtyField;
            }
            set {
                this.currentQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrentRejectQty {
            get {
                return this.currentRejectQtyField;
            }
            set {
                this.currentRejectQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ScrapQty {
            get {
                return this.scrapQtyField;
            }
            set {
                this.scrapQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal RejectedQty {
            get {
                return this.rejectedQtyField;
            }
            set {
                this.rejectedQtyField = value;
            }
        }
        
        /// <remarks/>
        public int Cartons {
            get {
                return this.cartonsField;
            }
            set {
                this.cartonsField = value;
            }
        }
        
        /// <remarks/>
        public int Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        public decimal AdjustQty {
            get {
                return this.adjustQtyField;
            }
            set {
                this.adjustQtyField = value;
            }
        }
        
        /// <remarks/>
        public TransformerDetail[] TransformerDetails {
            get {
                return this.transformerDetailsField;
            }
            set {
                this.transformerDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class TransformerDetail : EntityBase {
        
        private int idField;
        
        private int sequenceField;
        
        private string huIdField;
        
        private string itemCodeField;
        
        private string itemDescriptionField;
        
        private string uomCodeField;
        
        private decimal unitCountField;
        
        private string lotNoField;
        
        private string storageBinCodeField;
        
        private string statusField;
        
        private string locationCodeField;
        
        private int locationLotDetIdField;
        
        private int orderLocTransIdField;
        
        private string iOTypeField;
        
        private decimal qtyField;
        
        private decimal currentQtyField;
        
        private decimal currentRejectQtyField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string HuId {
            get {
                return this.huIdField;
            }
            set {
                this.huIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string UomCode {
            get {
                return this.uomCodeField;
            }
            set {
                this.uomCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitCount {
            get {
                return this.unitCountField;
            }
            set {
                this.unitCountField = value;
            }
        }
        
        /// <remarks/>
        public string LotNo {
            get {
                return this.lotNoField;
            }
            set {
                this.lotNoField = value;
            }
        }
        
        /// <remarks/>
        public string StorageBinCode {
            get {
                return this.storageBinCodeField;
            }
            set {
                this.storageBinCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        public int LocationLotDetId {
            get {
                return this.locationLotDetIdField;
            }
            set {
                this.locationLotDetIdField = value;
            }
        }
        
        /// <remarks/>
        public int OrderLocTransId {
            get {
                return this.orderLocTransIdField;
            }
            set {
                this.orderLocTransIdField = value;
            }
        }
        
        /// <remarks/>
        public string IOType {
            get {
                return this.iOTypeField;
            }
            set {
                this.iOTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrentQty {
            get {
                return this.currentQtyField;
            }
            set {
                this.currentQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrentRejectQty {
            get {
                return this.currentRejectQtyField;
            }
            set {
                this.currentRejectQtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserPreferenceBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserPreference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PermissionBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Permission))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiptNote))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransformerDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Transformer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resolver))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class EntityBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserPreference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class UserPreferenceBase : EntityBase {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class UserPreference : UserPreferenceBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Permission))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class PermissionBase : EntityBase {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class Permission : PermissionBase {
        
        private bool statusField;
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class UserBase : EntityBase {
        
        private string codeField;
        
        private string passwordField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string addressField;
        
        private string genderField;
        
        private string phoneField;
        
        private string mobliePhoneField;
        
        private bool isActiveField;
        
        private System.DateTime lastModifyDateField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string MobliePhone {
            get {
                return this.mobliePhoneField;
            }
            set {
                this.mobliePhoneField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastModifyDate {
            get {
                return this.lastModifyDateField;
            }
            set {
                this.lastModifyDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class User : UserBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class ReceiptNote : EntityBase {
        
        private int sequenceField;
        
        private string receiptNoField;
        
        private string ipNoField;
        
        private string orderNoField;
        
        private string partyFromField;
        
        private string partyToField;
        
        private string dockField;
        
        private System.DateTime createDateField;
        
        private string createUserField;
        
        private string huIdField;
        
        private string itemDescriptionField;
        
        private decimal unitCountField;
        
        private decimal qtyField;
        
        private string statusField;
        
        private string printUrlField;
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptNo {
            get {
                return this.receiptNoField;
            }
            set {
                this.receiptNoField = value;
            }
        }
        
        /// <remarks/>
        public string IpNo {
            get {
                return this.ipNoField;
            }
            set {
                this.ipNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string PartyFrom {
            get {
                return this.partyFromField;
            }
            set {
                this.partyFromField = value;
            }
        }
        
        /// <remarks/>
        public string PartyTo {
            get {
                return this.partyToField;
            }
            set {
                this.partyToField = value;
            }
        }
        
        /// <remarks/>
        public string Dock {
            get {
                return this.dockField;
            }
            set {
                this.dockField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public string HuId {
            get {
                return this.huIdField;
            }
            set {
                this.huIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitCount {
            get {
                return this.unitCountField;
            }
            set {
                this.unitCountField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string PrintUrl {
            get {
                return this.printUrlField;
            }
            set {
                this.printUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ScanBarcodeCompletedEventHandler(object sender, ScanBarcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScanBarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ScanBarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resolver Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resolver)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoadUserCompletedEventHandler(object sender, LoadUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserPermissionsCompletedEventHandler(object sender, GetUserPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permission[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permission[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoadUserPerferenceCompletedEventHandler(object sender, LoadUserPerferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadUserPerferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadUserPerferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserPreference Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserPreference)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591